### PR TITLE
fix #134 use the trusted top layer id from image info

### LINKED ISSUE #134: Layer order got reversed in v1.1.3, resulted in squashing parent layer instead of top layer.
~~Appending to the list `layers` got moved outside of the `if` block, resulted in a reversed list of `layers` than the previous version v1.1.0.~~

This would require subsequent change of `top_id = rld[-1]["id"]` to `top_id = rld[0]["id"]`. 

This is the root cause of why running squashed images for multi-layer images such as `ubuntu:16.04` will get  something like:
`Error: crun: executable file `/bin/bash` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found`.  Looking at the directory structure of `$SCRATCH/storage`, one would find the squash file pointing to the parent layer, not the top layer.

The version in v1.1.3

```python
        def _add_parent(layer, layer_map, layers=None, layer_ids=None):
            """
            Recrusive function to walk up parent graph.
            Inputs:
            layer: layer to walk
            layer_map: dictionary of layers by ID
            layers: list of layers that are being accumulated.
            layer_ids: accumulated dictionary of layers by ID
            """
            if not layer_ids:
                layer_ids = set()
            if not layers:
                layers = []
            logging.debug(f"Adding layer {layer['id']}")
            layers.append(layer)
            layer_ids.add(layer["id"])
            if "parent" in layer and layer["parent"] not in layer_ids:
                parent = layer_map[layer["parent"]]
                _add_parent(parent, layer_map, layers, layer_ids)
            return layers
```

old version in v1.1.0

```python
        def _add_parent(layer, layers, by_id, layer_ids):
            """
            Recrusive function to walk up parent graph.
            Inputs:
            layer: layer to walk
            layers: list of layers that are being accumulated.
            by_id: dictionary of layers by ID
            layer_ids: accumulated dictionary of layers by ID
            """
            if "parent" in layer and layer["parent"] not in layer_ids:
                parent = by_id[layer["parent"]]
                layers.append(parent)
                layer_ids.add(parent["id"])
                _add_parent(parent, layers, by_id, layer_ids)
```

### PR DESCRIPTION
**Pull request by dingp**

### CODE REVIEW

**Comment by dingp** [comment]
Ooops, sorry for containing `#` in the branch name. That makes the `pip install repo_URL@branch` fail, and no way to escape `#` there (a `pip` limitation).

**Comment by dingp** [comment]
Test procedure:

0. Install `podman-hpc` using this feature branch;
1. Find a a multi-layer image, inspect the image with `skopeo`, e.g.  `skopeo inspect docker://docker.io/ubuntu:16.04`
2. Pull the image;
3. List the image to verify it has been migrated;
4. Remove the local image with `podman-hpc rmi <img_id>`;
5. Run the container with the migrated image on the same node;
6. Run the container with the migrated image on a different login node;
7. Run the container with the migrated image on a compute node.

Test with the followinw images:
- `ubuntu:16.04`
- `nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04`
-  NERSC custom-built tensorflow image `registry.nersc.gov/library/nersc/tensorflow@ngc-24.05-v1`

**Comment by dingp** [comment]
It passed all my tests listed above. 

I also tested with a locally-built image where I added a file in the last (outermost) layer. The image was migrated with the patch version. I was able to see it in the squashed image on a compute node (container was running with podman-hpc v1.1.3).

**Comment by dingp** [comment]
I updated the version to `1.1.4`. If the PR is ready to merge, we can tag the main branch with `v1.1.4` right after the merge.

**Review by scanon — APPROVED** [review]
LGTM.  The key issue was the wrong layer was being linked up.  The actual squash image contents are correct because that uses the image ID.  But it was being attached to the wrong layer.

**Pull request merged**
